=== LightHaan/GeoPump-planner/public/data/schemas/climate.schema.json
{
  "additionalProperties": false,
  "properties": {
    "schema_version": {
      "const": "1.0.0",
      "title": "Schema Version",
      "type": "string"
    },
    "postcode": {
      "pattern": "^\\d{4}$",
      "title": "Postcode",
      "type": "string"
    },
    "time_basis": {
      "const": "UTC",
      "title": "Time Basis",
      "type": "string"
    },
    "record_type": {
      "const": "weighted_representative_hour",
      "title": "Record Type",
      "type": "string"
    },
    "record_layout": {
      "maxItems": 4,
      "minItems": 4,
      "prefixItems": [
        {
          "const": "day_of_year",
          "type": "string"
        },
        {
          "const": "hour_utc",
          "type": "string"
        },
        {
          "const": "air_temp_c",
          "type": "string"
        },
        {
          "const": "weight_hours",
          "type": "string"
        }
      ],
      "title": "Record Layout",
      "type": "array"
    },
    "record_count": {
      "minimum": 1,
      "title": "Record Count",
      "type": "integer"
    },
    "represented_hours": {
      "exclusiveMinimum": 0,
      "title": "Represented Hours",
      "type": "number"
    },
    "records": {
      "items": {
        "maxItems": 4,
        "minItems": 4,
        "prefixItems": [
          {
            "maximum": 366,
            "minimum": 1,
            "type": "integer"
          },
          {
            "exclusiveMaximum": 24,
            "minimum": 0,
            "type": "number"
          },
          {
            "type": "number"
          },
          {
            "exclusiveMinimum": 0,
            "type": "number"
          }
        ],
        "type": "array"
      },
      "title": "Records",
      "type": "array"
    }
  },
  "required": [
    "schema_version",
    "postcode",
    "time_basis",
    "record_type",
    "record_layout",
    "record_count",
    "represented_hours",
    "records"
  ],
  "title": "ClimateFile",
  "type": "object",
  "$schema": "https://json-schema.org/draft/2020-12/schema"
}

=== LightHaan/GeoPump-planner/public/data/climate/4488.json
{"schema_version":"1.0.0","postcode":"4488","time_basis":"UTC","record_type":"weighted_representative_hour","record_layout":["day_of_year","hour_utc","air_temp_c","weight_hours"],"record_count":1752,"represented_hours":8760.0,"records":[[1,0.0,29.402260742,5.0],[1,1.0,30.888850098,5.0],[1,2.0,32.028215332,5.0],[1,3.0,32.903818359,5.0],[1,4.0,33.5053125,5.0],[1,5.0,33.771030273,5.0],[1,6.0,33.570791016,5.0],[1,7.0,33.303532715,5.0],[1,8.0,32.531813965,5.0],[1,9.0,30.920268554999996,5.0],[1,10.0,28.856547852,5.0],[1,11.0,27.57177002,5.0],[1,12.0,26.581872558999997,5.0],[1,13.0,25.927304688,5.0],[1,14.0,25.238574219,5.0],[1,15.0,24.605866699,5.0],[1,16.0,24.086535644999998,5.0],[1,17.0,23.428439941,5.0],[1,18.0,22.856491699,5.0],[1,19.0,22.31239502,5.0],[1,20.0,22.728298340000002,5.0],[1,21.0,24.674362793,5.0],[1,22.0,26.458549804999997,5.0],[1,23.0,28.208615722999998,5.0],[6,0.0,29.865129395,5.0],[6,1.0,31.235332031,5.0],[6,2.0,32.373442383000004,5.0],[6,3.0,33.224880371,5.0],[6,4.0,33.841687012,5.0],[6,5.0,34.107302245999996,5.0],[6,6.0,33.970373535,5.0],[6,7.0,33.608364258,5.0],[6,8.0,32.807043457,5.0],[6,9.0,31.278200683999998,5.0],[6,10.0,29.295063477,5.0],[6,11.0,28.05638916,5.0],[6,12.0,27.121428223,5.0],[6,13.0,26.469138184,5.0],[6,14.0,25.889980469,5.0],[6,15.0,25.302788086,5.0],[6,16.0,24.707080078,5.0],[6,17.0,24.088041991999997,5.0],[6,18.0,23.519682616999997,5.0],[6,19.0,23.007824707,5.0],[6,20.0,23.242470703,5.0],[6,21.0,25.056464844,5.0],[6,22.0,26.766540527000004,5.0],[6,23.0,28.517380370999998,5.0],[11,0.0,30.153244629,5.0],[11,1.0,31.460444336000002,5.0],[11,2.0,32.571945801,5.0],[11,3.0,33.424611816,5.0],[11,4.0,33.969020996,5.0],[11,5.0,34.340585938,5.0],[11,6.0,34.224187012,5.0],[11,7.0,33.634484863,5.0],[11,8.0,32.804208984,5.0],[11,9.0,31.287978516,5.0],[11,10.0,29.314072265999997,5.0],[11,11.0,28.065288086,5.0],[11,12.0,27.302993164,5.0],[11,13.0,26.659487305,5.0],[11,14.0,26.099885254,5.0],[11,15.0,25.469135742,5.0],[11,16.0,24.853566895,5.0],[11,17.0,24.258278809,5.0],[11,18.0,23.67661377,5.0],[11,19.0,23.167663574,5.0],[11,20.0,23.354501953,5.0],[11,21.0,25.145341797,5.0],[11,22.0,26.879350586,5.0],[11,23.0,28.56310791,5.0],[16,0.0,30.40598877,5.0],[16,1.0,31.767988280999997,5.0],[16,2.0,32.877607422000004,5.0],[16,3.0,33.695229491999996,5.0],[16,4.0,34.269272461,5.0],[16,5.0,34.618659668,5.0],[16,6.0,34.481271973,5.0],[16,7.0,33.953769531,5.0],[16,8.0,33.073322754,5.0],[16,9.0,31.548845215,5.0],[16,10.0,29.511958008,5.0],[16,11.0,28.245717773000003,5.0],[16,12.0,27.469697265999997,5.0],[16,13.0,26.699016113,5.0],[16,14.0,26.197507324,5.0],[16,15.0,25.61890625,5.0],[16,16.0,25.098583984,5.0],[16,17.0,24.554819336,5.0],[16,18.0,23.983525390999997,5.0],[16,19.0,23.543061523000002,5.0],[16,20.0,23.573869629,5.0],[16,21.0,25.339577637,5.0],[16,22.0,27.133022461,5.0],[16,23.0,28.831035156,5.0],[21,0.0,30.35809082,5.0],[21,1.0,31.764812012000004,5.0],[21,2.0,32.881430664,5.0],[21,3.0,33.685288086,5.0],[21,4.0,34.338881836,5.0],[21,5.0,34.639211426,5.0],[21,6.0,34.429013672,5.0],[21,7.0,33.950778809,5.0],[21,8.0,33.068547363,5.0],[21,9.0,31.500749512000002,5.0],[21,10.0,29.629873047,5.0],[21,11.0,28.415288086,5.0],[21,12.0,27.508205566,5.0],[21,13.0,26.751269531,5.0],[21,14.0,26.216730957,5.0],[21,15.0,25.679470215000002,5.0],[21,16.0,25.211206054999998,5.0],[21,17.0,24.684008789,5.0],[21,18.0,24.110966797,5.0],[21,19.0,23.660854492,5.0],[21,20.0,23.565200195000003,5.0],[21,21.0,25.284724121,5.0],[21,22.0,27.060800780999998,5.0],[21,23.0,28.791291504,5.0],[26,0.0,30.267353516,5.0],[26,1.0,31.714545898,5.0],[26,2.0,32.786118164,5.0],[26,3.0,33.62314209,5.0],[26,4.0,34.225485840000005,5.0],[26,5.0,34.543110352,5.0],[26,6.0,34.385976562,5.0],[26,7.0,33.80331543,5.0],[26,8.0,32.926804198999996,5.0],[26,9.0,31.263918457,5.0],[26,10.0,29.523933105,5.0],[26,11.0,28.395205078,5.0],[26,12.0,27.441330566,5.0],[26,13.0,26.724956054999996,5.0],[26,14.0,26.149489746,5.0],[26,15.0,25.590935059,5.0],[26,16.0,25.084489746,5.0],[26,17.0,24.510930176000002,5.0],[26,18.0,23.943879395,5.0],[26,19.0,23.467424316000002,5.0],[26,20.0,23.276923827999997,5.0],[26,21.0,25.01708252,5.0],[26,22.0,26.850043945000003,5.0],[26,23.0,28.638823241999997,5.0],[31,0.0,29.617089844000002,5.0],[31,1.0,30.974877929999998,5.0],[31,2.0,32.135646973,5.0],[31,3.0,32.924111328,5.0],[31,4.0,33.444663086,5.0],[31,5.0,33.774345703,5.0],[31,6.0,33.666081543,5.0],[31,7.0,33.225048828,5.0],[31,8.0,32.367290039,5.0],[31,9.0,30.707961426,5.0],[31,10.0,28.943591309,5.0],[31,11.0,27.753615723,5.0],[31,12.0,26.909663086000002,5.0],[31,13.0,26.218830566,5.0],[31,14.0,25.580346679999998,5.0],[31,15.0,24.992182616999997,5.0],[31,16.0,24.532905273,5.0],[31,17.0,23.933076172,5.0],[31,18.0,23.384418945000004,5.0],[31,19.0,22.91590332,5.0],[31,20.0,22.615610351999997,5.0],[31,21.0,24.379985352,5.0],[31,22.0,26.286184082,5.0],[31,23.0,27.994245605,5.0],[36,0.0,29.027143555,5.0],[36,1.0,30.320510254000002,5.0],[36,2.0,31.471411133,5.0],[36,3.0,32.243598633000005,5.0],[36,4.0,32.718657227,5.0],[36,5.0,32.986337891,5.0],[36,6.0,32.917353516,5.0],[36,7.0,32.438322754,5.0],[36,8.0,31.687717284999998,5.0],[36,9.0,30.162497559,5.0],[36,10.0,28.390864258,5.0],[36,11.0,27.256503906,5.0],[36,12.0,26.407734375,5.0],[36,13.0,25.738017577999997,5.0],[36,14.0,25.150583496,5.0],[36,15.0,24.528571777000003,5.0],[36,16.0,24.083354491999998,5.0],[36,17.0,23.502111816000003,5.0],[36,18.0,23.016074219000004,5.0],[36,19.0,22.545219727,5.0],[36,20.0,22.154812012,5.0],[36,21.0,23.877646484000003,5.0],[36,22.0,25.779594727,5.0],[36,23.0,27.452790527,5.0],[41,0.0,29.176101073999998,5.0],[41,1.0,30.408054199,5.0],[41,2.0,31.490017090000002,5.0],[41,3.0,32.280895996,5.0],[41,4.0,32.74510498,5.0],[41,5.0,33.070256348,5.0],[41,6.0,32.961730957,5.0],[41,7.0,32.639841309,5.0],[41,8.0,31.943410645,5.0],[41,9.0,30.24333252,5.0],[41,10.0,28.375339355,5.0],[41,11.0,27.238239745999998,5.0],[41,12.0,26.359677734,5.0],[41,13.0,25.677092285,5.0],[41,14.0,25.027895508,5.0],[41,15.0,24.471918945000002,5.0],[41,16.0,24.004558105,5.0],[41,17.0,23.437309570000004,5.0],[41,18.0,22.976418457,5.0],[41,19.0,22.456440429999997,5.0],[41,20.0,22.068000488,5.0],[41,21.0,23.75942627,5.0],[41,22.0,25.774916991999998,5.0],[41,23.0,27.536188965,5.0],[46,0.0,29.28315918,5.0],[46,1.0,30.487963866999998,5.0],[46,2.0,31.534958495999998,5.0],[46,3.0,32.284267578,5.0],[46,4.0,32.747416992,5.0],[46,5.0,33.01829834,5.0],[46,6.0,32.844621582,5.0],[46,7.0,32.546938477,5.0],[46,8.0,31.705307617,5.0],[46,9.0,29.971901855000002,5.0],[46,10.0,28.1709375,5.0],[46,11.0,27.037260741999997,5.0],[46,12.0,26.191416015999998,5.0],[46,13.0,25.486054688,5.0],[46,14.0,24.910634765999998,5.0],[46,15.0,24.325737304999997,5.0],[46,16.0,23.856491699,5.0],[46,17.0,23.329150391,5.0],[46,18.0,22.853996582,5.0],[46,19.0,22.315185547000002,5.0],[46,20.0,21.905869140999997,5.0],[46,21.0,23.466848145,5.0],[46,22.0,25.574414062000002,5.0],[46,23.0,27.384008789,5.0],[51,0.0,28.897707519999997,5.0],[51,1.0,30.048901367,5.0],[51,2.0,31.199467773000002,5.0],[51,3.0,31.98637207,5.0],[51,4.0,32.497578125,5.0],[51,5.0,32.788024902000004,5.0],[51,6.0,32.659846191,5.0],[51,7.0,32.256022949,5.0],[51,8.0,31.421030273,5.0],[51,9.0,29.6715625,5.0],[51,10.0,27.951865234000003,5.0],[51,11.0,26.901010741999997,5.0],[51,12.0,26.150307617,5.0],[51,13.0,25.492290039,5.0],[51,14.0,24.922148438,5.0],[51,15.0,24.314702148000002,5.0],[51,16.0,23.85017334,5.0],[51,17.0,23.279345703,5.0],[51,18.0,22.804423827999997,5.0],[51,19.0,22.298000488,5.0],[51,20.0,21.883791504,5.0],[51,21.0,23.231311034999997,5.0],[51,22.0,25.155263672,5.0],[51,23.0,26.978457030999998,5.0],[56,0.0,28.30859375,5.0],[56,1.0,29.477722168,5.0],[56,2.0,30.645703125,5.0],[56,3.0,31.390541992,5.0],[56,4.0,31.965715332,5.0],[56,5.0,32.25135498,5.0],[56,6.0,32.144260254,5.0],[56,7.0,31.693388672,5.0],[56,8.0,30.815085448999998,5.0],[56,9.0,29.040593262,5.0],[56,10.0,27.398261719,5.0],[56,11.0,26.457856445,5.0],[56,12.0,25.840034179999996,5.0],[56,13.0,25.131801758,5.0],[56,14.0,24.661745605,5.0],[56,15.0,24.086374512000003,5.0],[56,16.0,23.564326172,5.0],[56,17.0,23.039743652000002,5.0],[56,18.0,22.517041015999997,5.0],[56,19.0,22.034072266,5.0],[56,20.0,21.641945801000002,5.0],[56,21.0,22.809587402000002,5.0],[56,22.0,24.633913573999997,5.0],[56,23.0,26.443317870999998,5.0],[61,0.0,27.581357422,5.0],[61,1.0,28.840515137,5.0],[61,2.0,29.939174804999997,5.0],[61,3.0,30.782939452999997,5.0],[61,4.0,31.302265625,5.0],[61,5.0,31.551967773,5.0],[61,6.0,31.407998047,5.0],[61,7.0,31.034709473,5.0],[61,8.0,30.110024413999998,5.0],[61,9.0,28.366513672,5.0],[61,10.0,26.699545898,5.0],[61,11.0,25.757731934,5.0],[61,12.0,25.073520508,5.0],[61,13.0,24.498615722999997,5.0],[61,14.0,23.954855957,5.0],[61,15.0,23.451899414,5.0],[61,16.0,22.883964844,5.0],[61,17.0,22.357871094000004,5.0],[61,18.0,21.866728516,5.0],[61,19.0,21.416113280999998,5.0],[61,20.0,20.993618164,5.0],[61,21.0,22.069951172,5.0],[61,22.0,24.014375,5.0],[61,23.0,25.833310547,5.0],[66,0.0,27.390686034999998,5.0],[66,1.0,28.667038574,5.0],[66,2.0,29.769577637,5.0],[66,3.0,30.649616699,5.0],[66,4.0,31.252546387000002,5.0],[66,5.0,31.497023926,5.0],[66,6.0,31.372478027000003,5.0],[66,7.0,30.946125487999996,5.0],[66,8.0,29.925871582,5.0],[66,9.0,27.924072266,5.0],[66,10.0,26.229272461,5.0],[66,11.0,25.262592773,5.0],[66,12.0,24.522526855000002,5.0],[66,13.0,23.863288574,5.0],[66,14.0,23.29796875,5.0],[66,15.0,22.699013672,5.0],[66,16.0,22.131862793,5.0],[66,17.0,21.57770752,5.0],[66,18.0,21.074335938,5.0],[66,19.0,20.534245605000002,5.0],[66,20.0,20.033684082,5.0],[66,21.0,21.19170166,5.0],[66,22.0,23.575754395,5.0],[66,23.0,25.562414551000003,5.0],[71,0.0,27.711691894999998,5.0],[71,1.0,29.100351562,5.0],[71,2.0,30.257436523000003,5.0],[71,3.0,31.161081543,5.0],[71,4.0,31.809487304999998,5.0],[71,5.0,32.052954102,5.0],[71,6.0,31.956704102,5.0],[71,7.0,31.474289551000002,5.0],[71,8.0,30.293952637000004,5.0],[71,9.0,27.966274414,5.0],[71,10.0,26.315075684,
